apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: goodbey
spec:
  params:
    - name: username
      type: string
  steps:
    - name: say-goodbey
      image: docker/whalesay
      script: |
        #!/usr/bin/env
        cowsay "Goodbye $(params.username)"
